CUDA_VISIBLE_DEVICES=1,2,3,4,5,6,7 accelerate launch --main_process_port  0 ./training/train_diffusion.py \
  --pretrained_model_name_or_path=./darcy/diff \
  --pretrained_vae_model_name_or_path=./darcy/vae \
  --pretrained_clip_model_name_or_path=./darcy/rep_ali\
  --dataset_name=darcy \
  --enable_xformers_memory_efficient_attention \
  --pretrained_sheduler_model_name_or_path=./sampler \
  --resolution=128 \
  --train_batch_size=32 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --max_train_steps=30000 \
  --learning_rate=1e-06 \
  --lr_scheduler=constant \
  --lr_warmup_steps=0 \
  --checkpointing_steps=500 \
  --output_dir=/data/ckpt_management_dir/my_diff_model \
  --config_path=./configs/darcy/ \
  --use_irr_o
