 python inference_data.py \
  --pretrained_model_name_or_path=./ns-nonbounded/diff \
  --pretrained_vae_model_name_or_path=./ns-nonbounded/vae \
  --pretrained_clip_model_name_or_path=./ns-nonbounded/rep_ali \
  --dataset_name=ns-nonbounded \
  --pretrained_sheduler_model_name_or_path=./sampler \
  --use_irr_data \
  --obs_guide_a_weight 0 \
  --obs_guide_u_weight 0.3 \
  --pde_guideweight 1 \
  --inference_steps 200 \
  --inverse
